# coding:utf-8
import sys

from PySide6.QtCore import QSize
from PySide6.QtWidgets import QApplication, QWidget

from FluentWidgets import FluentIcon, WinFluentIcon, PushButton, FlowLayout, VerticalScrollWidget, TitleLabel, \
    ToolButton


class IconDemo(VerticalScrollWidget):
    def __init__(self):
        super().__init__()
        self.flowLayout = FlowLayout()
        self.icons = {
            "FluentIcon": [
                FluentIcon.UP,
                FluentIcon.ADD,
                FluentIcon.BUS,
                FluentIcon.CAR,
                FluentIcon.CUT,
                FluentIcon.IOT,
                FluentIcon.PIN,
                FluentIcon.TAG,
                FluentIcon.VPN,
                FluentIcon.CAFE,
                FluentIcon.CHAT,
                FluentIcon.COPY,
                FluentIcon.CODE,
                FluentIcon.DOWN,
                FluentIcon.EDIT,
                FluentIcon.FLAG,
                FluentIcon.FONT,
                FluentIcon.GAME,
                FluentIcon.HELP,
                FluentIcon.HIDE,
                FluentIcon.HOME,
                FluentIcon.INFO,
                FluentIcon.LEAF,
                FluentIcon.LINK,
                FluentIcon.MAIL,
                FluentIcon.MENU,
                FluentIcon.MUTE,
                FluentIcon.MORE,
                FluentIcon.MOVE,
                FluentIcon.PLAY,
                FluentIcon.SAVE,
                FluentIcon.SEND,
                FluentIcon.SYNC,
                FluentIcon.UNIT,
                FluentIcon.VIEW,
                FluentIcon.WIFI,
                FluentIcon.ZOOM,
                FluentIcon.ALBUM,
                FluentIcon.BRUSH,
                FluentIcon.BROOM,
                FluentIcon.CLOSE,
                FluentIcon.CLOUD,
                FluentIcon.EMBED,
                FluentIcon.GLOBE,
                FluentIcon.HEART,
                FluentIcon.LABEL,
                FluentIcon.MEDIA,
                FluentIcon.MOVIE,
                FluentIcon.MUSIC,
                FluentIcon.ROBOT,
                FluentIcon.PAUSE,
                FluentIcon.PASTE,
                FluentIcon.PHOTO,
                FluentIcon.PHONE,
                FluentIcon.PRINT,
                FluentIcon.SHARE,
                FluentIcon.TILES,
                FluentIcon.UNPIN,
                FluentIcon.VIDEO,
                FluentIcon.TRAIN,
                FluentIcon.ADD_TO,
                FluentIcon.ACCEPT,
                FluentIcon.CAMERA,
                FluentIcon.CANCEL,
                FluentIcon.DELETE,
                FluentIcon.FOLDER,
                FluentIcon.FILTER,
                FluentIcon.MARKET,
                FluentIcon.SCROLL,
                FluentIcon.LAYOUT,
                FluentIcon.GITHUB,
                FluentIcon.UPDATE,
                FluentIcon.REMOVE,
                FluentIcon.RETURN,
                FluentIcon.PEOPLE,
                FluentIcon.QRCODE,
                FluentIcon.RINGER,
                FluentIcon.ROTATE,
                FluentIcon.SEARCH,
                FluentIcon.VOLUME,
                FluentIcon.FRIGID,
                FluentIcon.SAVE_AS,
                FluentIcon.ZOOM_IN,
                FluentIcon.CONNECT,
                FluentIcon.HISTORY,
                FluentIcon.SETTING,
                FluentIcon.PALETTE,
                FluentIcon.MESSAGE,
                FluentIcon.FIT_PAGE,
                FluentIcon.ZOOM_OUT,
                FluentIcon.AIRPLANE,
                FluentIcon.ASTERISK,
                FluentIcon.CALORIES,
                FluentIcon.CALENDAR,
                FluentIcon.FEEDBACK,
                FluentIcon.LIBRARY,
                FluentIcon.MINIMIZE,
                FluentIcon.CHECKBOX,
                FluentIcon.DOCUMENT,
                FluentIcon.LANGUAGE,
                FluentIcon.DOWNLOAD,
                FluentIcon.QUESTION,
                FluentIcon.SPEAKERS,
                FluentIcon.DATE_TIME,
                FluentIcon.FONT_SIZE,
                FluentIcon.HOME_FILL,
                FluentIcon.PAGE_LEFT,
                FluentIcon.SAVE_COPY,
                FluentIcon.SEND_FILL,
                FluentIcon.SKIP_BACK,
                FluentIcon.SPEED_OFF,
                FluentIcon.ALIGNMENT,
                FluentIcon.BLUETOOTH,
                FluentIcon.COMPLETED,
                FluentIcon.CONSTRACT,
                FluentIcon.HEADPHONE,
                FluentIcon.MEGAPHONE,
                FluentIcon.PROJECTOR,
                FluentIcon.EDUCATION,
                FluentIcon.LEFT_ARROW,
                FluentIcon.ERASE_TOOL,
                FluentIcon.PAGE_RIGHT,
                FluentIcon.PLAY_SOLID,
                FluentIcon.HIGHTLIGHT,
                FluentIcon.FOLDER_ADD,
                FluentIcon.PAUSE_BOLD,
                FluentIcon.PENCIL_INK,
                FluentIcon.PIE_SINGLE,
                FluentIcon.QUICK_NOTE,
                FluentIcon.SPEED_HIGH,
                FluentIcon.STOP_WATCH,
                FluentIcon.ZIP_FOLDER,
                FluentIcon.BASKETBALL,
                FluentIcon.BRIGHTNESS,
                FluentIcon.DICTIONARY,
                FluentIcon.MICROPHONE,
                FluentIcon.ARROW_DOWN,
                FluentIcon.FULL_SCREEN,
                FluentIcon.MIX_VOLUMES,
                FluentIcon.REMOVE_FROM,
                FluentIcon.RIGHT_ARROW,
                FluentIcon.QUIET_HOURS,
                FluentIcon.FINGERPRINT,
                FluentIcon.APPLICATION,
                FluentIcon.CERTIFICATE,
                FluentIcon.TRANSPARENT,
                FluentIcon.IMAGE_EXPORT,
                FluentIcon.SPEED_MEDIUM,
                FluentIcon.LIBRARY_FILL,
                FluentIcon.MUSIC_FOLDER,
                FluentIcon.POWER_BUTTON,
                FluentIcon.SKIP_FORWARD,
                FluentIcon.CARE_UP_SOLID,
                FluentIcon.ACCEPT_MEDIUM,
                FluentIcon.CANCEL_MEDIUM,
                FluentIcon.CHEVRON_RIGHT,
                FluentIcon.CLIPPING_TOOL,
                FluentIcon.SEARCH_MIRROR,
                FluentIcon.SHOPPING_CART,
                FluentIcon.FONT_INCREASE,
                FluentIcon.BACK_TO_WINDOW,
                FluentIcon.COMMAND_PROMPT,
                FluentIcon.CLOUD_DOWNLOAD,
                FluentIcon.DICTIONARY_ADD,
                FluentIcon.CARE_DOWN_SOLID,
                FluentIcon.CARE_LEFT_SOLID,
                FluentIcon.CLEAR_SELECTION,
                FluentIcon.DEVELOPER_TOOLS,
                FluentIcon.BACKGROUND_FILL,
                FluentIcon.CARE_RIGHT_SOLID,
                FluentIcon.CHEVRON_DOWN_MED,
                FluentIcon.CHEVRON_RIGHT_MED,
                FluentIcon.EMOJI_TAB_SYMBOLS,
                FluentIcon.EXPRESSIVE_INPUT_ENTRY
            ],
            "WinFluentIcon": [
                WinFluentIcon.CALC,
                WinFluentIcon.CHAT,
                WinFluentIcon.DOWN,
                WinFluentIcon.HOME,
                WinFluentIcon.LEFT,
                WinFluentIcon.LIKE,
                WinFluentIcon.LINK,
                WinFluentIcon.MENU,
                WinFluentIcon.NEWS,
                WinFluentIcon.PLAY,
                WinFluentIcon.SEND,
                WinFluentIcon.SAVE,
                WinFluentIcon.WIFI,
                WinFluentIcon.TOOL,
                WinFluentIcon.INFO,
                WinFluentIcon.HELP,
                WinFluentIcon.MORE,
                WinFluentIcon.SIGN,
                WinFluentIcon.MUSIC,
                WinFluentIcon.PAINT,
                WinFluentIcon.DOUBT,
                WinFluentIcon.CLOUD,
                WinFluentIcon.CHECK,
                WinFluentIcon.RIGHT,
                WinFluentIcon.ROUND,
                WinFluentIcon.FOLDER,
                WinFluentIcon.FINISH,
                WinFluentIcon.RETURN,
                WinFluentIcon.ATTACH,
                WinFluentIcon.XIAN_JI,
                WinFluentIcon.XIN_HAO,
                WinFluentIcon.RE_BOOT,
                WinFluentIcon.SORT_UP,
                WinFluentIcon.DROP_UP,
                WinFluentIcon.MESSAGE,
                WinFluentIcon.FORWARD,
                WinFluentIcon.WEATHER,
                WinFluentIcon.ADDRESS,
                WinFluentIcon.WARNING,
                WinFluentIcon.SETTING,
                WinFluentIcon.COMMENT,
                WinFluentIcon.CONTACT,
                WinFluentIcon.NOTEPAD,
                WinFluentIcon.MAN_USER,
                WinFluentIcon.SHI_ZHON,
                WinFluentIcon.ADD_CHAT,
                WinFluentIcon.GO_AHEAD,
                WinFluentIcon.ADD_LINK,
                WinFluentIcon.CALENDAR,
                WinFluentIcon.EXPLORER,
                WinFluentIcon.TERMINAL,
                WinFluentIcon.DATA_BASE,
                WinFluentIcon.SUN_CLOUD,
                WinFluentIcon.EDIT_FILE,
                WinFluentIcon.ADD_EMAIL,
                WinFluentIcon.MSF_STORE,
                WinFluentIcon.SORT_LEFT,
                WinFluentIcon.DROP_DOWN,
                WinFluentIcon.DROP_LEFT,
                WinFluentIcon.SORT_DOWN,
                WinFluentIcon.MICROSOFT,
                WinFluentIcon.WIN_11_LOG,
                WinFluentIcon.IMAGE_FILE,
                WinFluentIcon.SORT_RIGHT,
                WinFluentIcon.ZIP_FOLDER,
                WinFluentIcon.DROP_RIGHT,
                WinFluentIcon.DEL_FOLDER,
                WinFluentIcon.ADD_FOLDER,
                WinFluentIcon.ERROR_LINK,
                WinFluentIcon.NO_NETWORK,
                WinFluentIcon.QUICK_SHARK,
                WinFluentIcon.FEMAIL_USER,
                WinFluentIcon.GAME_FOLDER,
                WinFluentIcon.RECYCLE_BIN,
                WinFluentIcon.CODE_FOLDER,
                WinFluentIcon.SEARCH_CHAT,
                WinFluentIcon.SEARCH_MORE,
                WinFluentIcon.MUSIC_FOLDER,
                WinFluentIcon.CHAT_MESSAGE,
                WinFluentIcon.CLOUD_FOLDER,
                WinFluentIcon.CHAT_BUBBLES,
                WinFluentIcon.VIDEO_FOLDER,
                WinFluentIcon.RIGHT_SING_IN,
                WinFluentIcon.ROTATION_LEFT,
                WinFluentIcon.EDIT_CALENDAR,
                WinFluentIcon.EMAILO_MESSAGE,
                WinFluentIcon.MOVE_TO_FOLDER,
                WinFluentIcon.COPY_TO_FOLDER,
                WinFluentIcon.ROTATION_RIGHT,
                WinFluentIcon.DOWNLOAD_CLOUD,
                WinFluentIcon.PICTURE_FOLDER,
                WinFluentIcon.DOWNLOAD_FOLDER,
                WinFluentIcon.DOCUMENT_FOLDER,
                WinFluentIcon.RADIUS_WIN_11_LOG,
                WinFluentIcon.ADD_EMAIL_MESSAGE,
                WinFluentIcon.DOWNLOAD_FROM_THE_CLOUD
            ]
        }

        self.addLayout(self.flowLayout)
        for _ in self.icons["FluentIcon"]:
            button = ToolButton(_, self)
            button.setFixedSize(100, 100)
            button.setIconSize(QSize(32, 32))
            self.flowLayout.addWidget(button)

        for _ in self.icons["WinFluentIcon"]:
            button = ToolButton(_, self)
            button.setFixedSize(100, 100)
            button.setIconSize(QSize(32, 32))
            self.flowLayout.addWidget(button)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    window = IconDemo()
    window.resize(800, 520)
    window.show()
    sys.exit(app.exec())